/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posttest2;

/**
 *
 * @author Gidion
 */
public class FormKTP extends javax.swing.JFrame {

    /**
     * Creates new form FormKTP
     */
    public FormKTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        KTP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        TTL = new javax.swing.JLabel();
        JK = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        RT = new javax.swing.JLabel();
        Kdesa = new javax.swing.JLabel();
        TF_nama = new javax.swing.JTextField();
        TF_tempat = new javax.swing.JTextField();
        TF_alamat = new javax.swing.JTextField();
        Kec = new javax.swing.JLabel();
        Kota = new javax.swing.JLabel();
        Agama = new javax.swing.JLabel();
        TF_rt = new javax.swing.JTextField();
        TF_desa = new javax.swing.JTextField();
        TF_kota = new javax.swing.JTextField();
        TF_kec = new javax.swing.JTextField();
        Status = new javax.swing.JLabel();
        Pekerjaan = new javax.swing.JLabel();
        Goldar = new javax.swing.JLabel();
        KW = new javax.swing.JLabel();
        cb_agama = new javax.swing.JComboBox<String>();
        cb_status = new javax.swing.JComboBox<String>();
        cb_goldar = new javax.swing.JComboBox<String>();
        TF_pekerjaan = new javax.swing.JTextField();
        wna = new javax.swing.JRadioButton();
        Lk = new javax.swing.JRadioButton();
        Pr = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        TF_lahir = new javax.swing.JTextField();
        TF_rw = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        wni = new javax.swing.JRadioButton();
        Reset = new javax.swing.JButton();
        Register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KTP.setBackground(new java.awt.Color(51, 0, 255));
        KTP.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel1.setText("                 KARTU TANDA PENDUDUK");

        Nama.setText("Nama");

        TTL.setText("Tempat/Tanggal Lahir");

        JK.setText("Jenis Kelamin");

        Alamat.setText("Alamat");

        RT.setText("RT/RW");

        Kdesa.setText("Kel/Desa");

        Kec.setText("Kecamatan");

        Kota.setText("Kota");

        Agama.setText("Agama");

        Status.setText("Status");

        Pekerjaan.setText("Pekerjaan");

        Goldar.setText("Golongan Darah");

        KW.setText("Kewarganegaraan");

        cb_agama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Katholik", "Kristen", "Islam", "Konghuchu" }));

        cb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kawin", "Belum Kawin", "Janda", "Duda", " " }));

        cb_goldar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "O" }));

        TF_pekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_pekerjaanActionPerformed(evt);
            }
        });

        buttonGroup2.add(wna);
        wna.setText("WNA");

        buttonGroup1.add(Lk);
        Lk.setText("Laki-Laki");

        buttonGroup1.add(Pr);
        Pr.setText("Perempuan");

        jLabel15.setText("/");

        TF_lahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_lahirActionPerformed(evt);
            }
        });

        jLabel16.setText("/");

        buttonGroup2.add(wni);
        wni.setText("WNI");

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KTPLayout = new javax.swing.GroupLayout(KTP);
        KTP.setLayout(KTPLayout);
        KTPLayout.setHorizontalGroup(
            KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KTPLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Kdesa)
                    .addComponent(RT)
                    .addComponent(Kec)
                    .addComponent(Kota))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(KTPLayout.createSequentialGroup()
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama)
                    .addComponent(Alamat)
                    .addComponent(JK)
                    .addComponent(TTL)
                    .addComponent(Agama)
                    .addComponent(Status)
                    .addComponent(Goldar)
                    .addComponent(Pekerjaan)
                    .addComponent(KW))
                .addGap(81, 81, 81)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_tempat))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 45, Short.MAX_VALUE))
                            .addComponent(Pr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(wna)
                                .addGap(18, 18, 18)
                                .addComponent(wni))
                            .addComponent(cb_goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TF_kota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(TF_kec, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TF_desa, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(TF_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_rw, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TF_pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                        .addComponent(Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Register))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        KTPLayout.setVerticalGroup(
            KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KTPLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(TF_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TTL)
                    .addComponent(TF_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TF_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JK)
                    .addComponent(Lk)
                    .addComponent(Pr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alamat)
                    .addComponent(TF_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RT)
                    .addComponent(TF_rt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_rw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kdesa)
                    .addComponent(TF_desa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kec)
                    .addComponent(TF_kec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kota)
                    .addComponent(TF_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agama)
                    .addComponent(cb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status)
                    .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Goldar)
                    .addComponent(cb_goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pekerjaan)
                    .addComponent(TF_pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KW)
                    .addComponent(wna)
                    .addComponent(wni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register)
                    .addComponent(Reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_lahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_lahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_lahirActionPerformed

    private void TF_pekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_pekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_pekerjaanActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        OutputKTP output = new OutputKTP ();
        output.TF_nama.setText(TF_nama.getText());
        output.TF_TTL1.setText(TTL.getText());
        output.TF_lahir1.setText(TTL.getText());
        output.TF_JK.setText(JK.getText());
        output.TF_alamat.setText(Alamat.getText());
        output.TF_rt.setText(RT.getText());
        output.TF_rw.setText(RT.getText());
        output.TF_kdesa.setText(Kdesa.getText());
        output.TF_kec.setText(Kec.getText());
        output.TF_kota.setText(Kota.getText());
        output.TF_agama.setText(this.cb_agama.getSelectedItem().toString());
        output.TF_status.setText(this.cb_status.getSelectedItem().toString());
        output.TF_goldar.setText(this.cb_goldar.getSelectedItem().toString());
        output.TF_pekerjaan.setText(Pekerjaan.getText());
        
        
        String Agama = cb_agama.getSelectedItem().toString();
        String Status = cb_status.getSelectedItem().toString();
        String Goldar = cb_goldar.getSelectedItem().toString();

        
        String JK = null;
        if (Lk.isSelected())
            output.TF_JK.setText(this.Lk.getText());
        else if (Lk.isSelected())
            output.TF_JK.setText(this.Pr.getText());
        
        
        String KW = null ;
        /**
        if (wna.isSelected())
            output.TF_kw.setText(this.wna.getText());
        else if (wni.isSelected())
            output.TF_kw.setText(this.wni.getText());
        **/
        if (wna.isSelected())
            output.TF_kwn.setText(this.wna.getText());
        else if (wni.isSelected())
            output.TF_kwn.setText(this.wni.getText());
        
        output.setVisible(true);
    }//GEN-LAST:event_RegisterActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        TF_nama.setText("");
        TF_tempat.setText("");
        TF_lahir.setText("");
        TF_alamat.setText("");
        TF_rt.setText("");
        TF_rw.setText("");
        TF_desa.setText("");
        TF_kec.setText("");
        TF_kota.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        TF_pekerjaan.setText("");



    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agama;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Goldar;
    private javax.swing.JLabel JK;
    private javax.swing.JPanel KTP;
    private javax.swing.JLabel KW;
    private javax.swing.JLabel Kdesa;
    private javax.swing.JLabel Kec;
    private javax.swing.JLabel Kota;
    private javax.swing.JRadioButton Lk;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Pekerjaan;
    private javax.swing.JRadioButton Pr;
    private javax.swing.JLabel RT;
    private javax.swing.JButton Register;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel Status;
    private javax.swing.JTextField TF_alamat;
    private javax.swing.JTextField TF_desa;
    private javax.swing.JTextField TF_kec;
    private javax.swing.JTextField TF_kota;
    private javax.swing.JTextField TF_lahir;
    private javax.swing.JTextField TF_nama;
    private javax.swing.JTextField TF_pekerjaan;
    private javax.swing.JTextField TF_rt;
    private javax.swing.JTextField TF_rw;
    private javax.swing.JTextField TF_tempat;
    private javax.swing.JLabel TTL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_agama;
    private javax.swing.JComboBox<String> cb_goldar;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JRadioButton wna;
    private javax.swing.JRadioButton wni;
    // End of variables declaration//GEN-END:variables
}
